#!/bin/bash
xmessage "the INSTALLNEEDEDLIBS program will fail if IT not run in terminal"
xmessage "installing kdialog[ENTER PASSWORD or run as ROOT]" &
sudo su
apt-get install kdialog
kdialog --msgbox "if you see this, the \"libs\" are installed SUCESSFULLY" &
sleep 60
